// app/layout.tsx
import React from 'react';
// import '../../app/global.css'; // Optional: import global styles

export const metadata = {
  title: 'My Next.js App',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main className='flex flex-col items-center justify-center h-screen'>{children}</main>
      </body>
    </html>
  );
}
